### ISSUE TITLE
CamelCased names

### ISSUE THREAD

**Issue by casper2002casper** [actions-on-google/smart-home-schema#3]
It would be nice to have all trait and command names camelcased as there is currently no way to get those from the git and they are need for the sync fulfillment

**Comment by i8beef** [comment]
Matching case to the actual trait / command name would be nice. The lack of a comprehensive "trait" list like there is with "devices" is one of the holes in my implementation now... but a directory listing would be close, even though it wouldn't be ideal since we still couldn't get metadata like trait name, etc.

**Comment by proppy** [comment]
We now have platform level enum schema for traits / commands / and device types, see: 06c1127
